name: printer_module
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  file_picker: ^11.0.2
  permission_handler:
  hive:
  hive_flutter:
  flutter_slidable: ^3.0.1
  csv: ^5.0.1
  logger: ^1.1.0
  blue_thermal_printer:
    git:
      url: https://github.com/raihanArman/blue_thermal_printer.git
      ref: master
  intl: ^0.17.0
  share_plus: ^10.0.0
  path_provider: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

